### ISSUE TITLE
gif.icon 

### ISSUE THREAD

**Issue by peareye** [wolfmoritz/ppfr#21]
the browser gif.icon seems to randomly show up and randomly not be there.
![screen shot 2016-06-08 at 12 27 14 pm](https://cloud.githubusercontent.com/assets/11490640/15908034/6d7826c4-2d74-11e6-9a4f-58e3ead0df10.png)

**Comment by wolfmoritz** [comment]
The links to the various favicons and apple-touch-icons were all relative to the current page (because of the lack of a leading slash), not the domain root. So for Tartar sauce the page was looking for a favicon located at http://perisplaceforrecipes.com/recipe/show/206/favicon.ico, which does not exist. It's possible the other recipe pages showed the favicon just because of browser caching.

I added a Twig tag `recipe.basePath` which prints the project folder if working on localhost, and blank if on production, followed by a leading slash. This way all favicon and tiles use a reference to the domain/web root.

1857062
